### ISSUE TITLE
Fatal error: Arrays are not allowed in class constants. Fix?

### ISSUE THREAD

**Issue by WriterStat** [MarijnMensinga/basic-HTML-to-RTF-converter#1]
Wanted to check this out.

Got this error when trying the code the first time.

Fatal error: Arrays are not allowed in class constants in /home3/ccatlin1/public_html/pinboardtest/test/src/HtmlToRtf.php on line 17

Any fix to apply? Thanks! Am using php 5.45, but can set it to anyone needed. 

Will also check the code myself, and see for a fix, but wanted to quick ask b4 making changes.

Best, looking forward to trying this,

-C

**Comment by MarijnMensinga** [comment]
You should use PHP 5.6+

**Comment by WriterStat** [comment]
Thanks for the awesome quick reply! And the cool code to try out.

Did that just after posting here, figured it might be 5.6. Can report it works like a charm! All the hosting here is set at 5.45. =) Thanks again!

Going to check it on 7

Best,

-C
